- hosts: master
  become: true
  become_user: root
  tasks:
  - name: copy kubectl script
    copy: src=./get_kubectl.sh dest=/root/get_kubectl.sh mode=0755
  - name: copy kubectl config script
    copy: src=./kube_connect.sh dest=/root/kube_connect.sh mode=0755
  - name: get kubectl
    script: ./get_kubectl.sh creates=/usr/local/bin/kubectl
  - name: configure kubectl
    script: ./kube_connect.sh kube-master.opsits.com creates=/root/.kube/config
  - name: get skydns service description
    copy: src=./skydns.yaml dest=/root/skydns.yaml mode=0755
  - name: enable DNS service
    command: kubectl create -f ./skydns.yaml
