---
- hosts: all
  pre_tasks:
  - name: install system specific packages
    include: Debian.yml
    when: ansible_os_family == "Debian"
  - name: install RedHat specific packages
    include: Redhat.yml
    when: ansible_os_family == "RedHat"
  tasks:
#  - name: get docker install script
#    get_url: url=https://get.docker.com/ dest=docker.sh mode=0755 validate_certs=False
  - name: get docker install script
    shell: curl -sSL https://get.docker.com > ./docker.sh creates=/root/docker.sh
- hosts: minion
  become: true
  become_user: root
  tasks:
  - name: ensure docker is running
    service: name=docker state=started
  - name: run setup script
    shell: "FLANNEL_IFACE=bond0 K8S_VERSION=1.2.0-beta.1 MASTER_IP={{hostvars['kube-master.opsits.com']['ansible_bond0']['ipv4']['address']}} ./worker.sh"
    args:
      chdir: /root/kubernetes/docs/getting-started-guides/docker-multinode/
      executable: /bin/bash
