---
- hosts: all
  become: true
  become_user: root
  vars:
    interface_name: 
  pre_tasks:
  - name: install system specific packages
    include: Debian.yml
    when: ansible_os_family == "Debian"
  - name: install RedHat specific packages
    include: Redhat.yml
    when: ansible_os_family == "RedHat"
  tasks:
  - name: get docker install script
    get_url: url=https://get.docker.com/ dest=docker.sh mode=0755 
  - name: install docker from docker script
    command: /bin/sh docker.sh creates=/etc/docker/key.json
  - name: get kubernets git repo
    git: repo=https://github.com/kubernetes/kubernetes dest=/root/kubernetes
- hosts: master
  become: true
  become_user: root
  tasks:
  - name: ensure docker is running
    service: name=docker state=started
  - name: run setup script
    shell: "K8S_VERSION=1.2.0-beta.1 MASTER_IP={{hostvars['kube-master.opsits.com']['ansible_team0']['ipv4']['address']}} ./master.sh"
    args:
      chdir: /root/kubernetes/docs/getting-started-guides/docker-multinode/
      executable: /bin/bash
- hosts: minion
  become: true
  become_user: root
  tasks:
  - name: ensure docker is running
    service: name=docker state=started
  - name: run setup script
    shell: "K8S_VERSION=1.2.0-beta.1 MASTER_IP={{hostvars['kube-master.opsits.com']['ansible_team0']['ipv4']['address']}} ./worker.sh"
    args:
      chdir: /root/kubernetes/docs/getting-started-guides/docker-multinode/
      executable: /bin/bash
