---
- hosts: minion
  tasks:
  - name: add sfdisk script
    copy: src=./sfdisk-nvme.sh dest=/root/sfdisk-nvme.sh mode=0755
  - name: run sfdisk script
    command: /root/sfdisk-nvme.sh creates=/mnt/nvme1
