---
- hosts: all
  become: true
  become_user: root
  vars:
    interface_name:
  pre_tasks:
  - name: install system specific packages
    include: Debian.yml
    when: ansible_os_family == "Debian"
  - name: install RedHat specific packages
    include: Redhat.yml
    when: ansible_os_family == "RedHat"
  - name: get the hostnames configured properly
    include: hosts.yml
  - name: set up additionl ssh authorized_keys
    include: keys.yml
  tasks:
  - name: get docker install script
    shell: curl -sSL https://get.docker.com > ./docker.sh creates=/root/docker.sh
  - name: install docker from docker script
    command: /bin/sh docker.sh creates=/etc/docker/key.json
- hosts: master
  become: true
  become_user: root
  tasks:
  - name: ensure docker is running
    service: name=docker state=started
  - name: copy master.sh script to master node
    copy: src=./master.sh dest=/root/master.sh mode=0755
  - name: run setup script
    shell: "FLANNEL_IFACE=eth0 K8S_VERSION=1.2.0 MASTER_IP={{hostvars['master.opsits.com']['ansible_eth0']['ipv4']['address']}} ./master.sh"
    args:
      executable: /bin/bash
      creates: /etc/systemd/system/docker.service.d/flannel-subnet.conf
  - name: copy kubectl script
    copy: src=./get_kubectl.sh dest=/root/get_kubectl.sh mode=0755
  - name: copy kubectl config script
    copy: src=./kube_connect.sh dest=/root/kube_connect.sh mode=0755
  - name: get kubectl
    script: ./get_kubectl.sh creates=/usr/local/bin/kubectl
  - name: configure kubectl
    script: ./kube_connect.sh master.opsits.com creates=/root/.kube/config
- hosts: minion
  become: true
  become_user: root
  tasks:
  - name: ensure docker is running
    service: name=docker state=started
  - name: copy worker.sh script to worker node
    copy: src=./worker.sh dest=/root/worker.sh mode=0755
  - name: run setup script
    shell: "FLANNEL_IFACE=eth0 K8S_VERSION=1.2.2 MASTER_IP={{hostvars['master.opsits.com']['ansible_eth0']['ipv4']['address']}} ./worker.sh"
    args:
      executable: /bin/bash
      creates: /etc/systemd/system/docker.service.d/flannel-subnet.conf
- hosts: master
  become: true
  become_user: root
  tasks:
  - name: get skydns service description
    copy: src=./skydns.yaml dest=/root/skydns.yaml mode=0755
  - name: enable DNS service
    command: kubectl create -f ./skydns.yaml
  - name: install ycsb
    include: ycsb.yml
